io:
  logdir: logs/
  datadir: /home/dxl/Data/LondonCity/renderings_plane/20200222
  dataset: LONDONCITY
  resume_from:
  num_workers: 6

model:
  batch_size: 256
  fc_channel: 1024

optim:
  name: Adam
  lr: 4.0e-4
  amsgrad: True
  weight_decay: 1.0e-4
  max_epoch: 36
  lr_decay_epoch: 24
